### ISSUE TITLE
Missing bracket in the demo code on main page

### ISSUE THREAD

**Issue by Machinas** [wikimedia/html-metadata#43]
The closing bracket for the "options" variable is missing, only "headers" is closed correctly in the example code for the Options object:

var options =  {
        url: "http://blog.woorank.com/2013/04/dublin-core-metadata-for-seo-and-usability/",
        jar: request.jar(), // Cookie jar
        headers: {
            'User-Agent': 'webscraper'
        }

**Comment by mvolz** [comment]
Thanks for reporting this! Fixed.
