### ISSUE TITLE
Receiving HTTPError: 403 from Shopify Sites

### ISSUE THREAD

**Issue by mbillz** [wikimedia/html-metadata#78]
This library is working great in all areas except when we try to scrape a Shopify site. When running the main scrape function the JSON response returned is an error message with string "Receiving HTTPError: 403 from Shopify Sites".

Any guidance? You can reproduce from the Node app we setup at https://metaparser-v2.thesocialpresskit.com by passing a url in as a query argument. A Shopify example of this is https://metaparser-v2.thesocialpresskit.com/?url=https://sincerelyjewelry.com/

Thanks in advance for any help!!

**Comment by mvolz** [comment]
Have you tried setting a cookie in the options object?

**Comment by mbillz** [comment]
we ended up moving to a different library. thanks though!
